package biblioteca;

import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ariel
 */
public class ModificarGUI extends javax.swing.JFrame {
 
      private RandomAccessFile raf;
      
    private Libro readLibro(int num) throws IOException {
        
         raf.seek(num * Libro.SIZE);
        byte[] record = new byte[Libro.SIZE];
        raf.read(record);
        return Libro.fromBytes(record);
    }
     private void writeLibro(int num, Libro libro) throws IOException {
    raf.seek(num * Libro.SIZE);
    byte[] record = libro.toBytes();
    raf.write(record);
}
   

   public ModificarGUI() {
         initComponents();
        
        try {
            
            raf = new RandomAccessFile("Biblioteca.dat", "rw");
         
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo");
            Logger.getLogger(ModificarGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtISDN = new javax.swing.JTextField();
        txtNoPaginas = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtPrestado = new javax.swing.JTextField();
        txtFechaPres = new javax.swing.JTextField();
        txtNomPres = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        txtFechaAdqui = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtLeido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Libros");
        setLocation(new java.awt.Point(700, 300));
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("Modificar libros ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Fecha_adquisicion");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Titulo");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("ISDN");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("NO. Paginas");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Precio");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Prestado");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Fecha de Prestamo");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("NombrePrestamo");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Autor");

        txtTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTitulo.setName("txtTitulo"); // NOI18N

        txtISDN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtISDN.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtISDN.setName("txtISDN"); // NOI18N

        txtNoPaginas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNoPaginas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNoPaginas.setName("txtNoPaginas"); // NOI18N

        txtPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPrecio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecio.setName("txtPrecio"); // NOI18N

        txtPrestado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPrestado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrestado.setName("txtPrestado"); // NOI18N

        txtFechaPres.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFechaPres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFechaPres.setName("txtFechaPres"); // NOI18N

        txtNomPres.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNomPres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNomPres.setName("txtNomPres"); // NOI18N

        txtAutor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtAutor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAutor.setName("txtAutor"); // NOI18N

        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setName("btnAceptar"); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtFechaAdqui.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtFechaAdqui.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFechaAdqui.setName("txtFechaAdqui"); // NOI18N

        jLabel11.setText("Numero de Indice");

        txtIndice.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txtIndice.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIndice.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIndice.setName("txtIndice"); // NOI18N

        jLabel12.setText("Leido");

        txtLeido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLeido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLeido.setName("txtNoPaginas"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAutor)
                            .addComponent(txtNoPaginas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISDN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIndice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLeido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomPres, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFechaAdqui, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(txtFechaPres))
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrestado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPrestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFechaAdqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFechaPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtISDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNoPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtLeido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
        int indice = Integer.parseInt(txtIndice.getText());
        
        // Validar el índice ingresado
        if (indice < 0) {
            JOptionPane.showMessageDialog(this, "El índice debe ser mayor o igual a cero");
            return;
        }
        
        Libro libro = readLibro(indice);
        
        // Verificar si el libro existe en el índice indicado
        if (libro == null) {
            JOptionPane.showMessageDialog(this, "No existe un libro en el índice indicado");
            return;
        }
      
        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        String isbn = txtISDN.getText();
        int noPaginas = Integer.parseInt(txtNoPaginas.getText());
        int precio = Integer.parseInt(txtPrecio.getText());
        String fechaAdq = txtFechaAdqui.getText();
        boolean prestado = Boolean.parseBoolean(txtPrestado.getText());
        boolean leido= Boolean.parseBoolean(txtLeido.getText());
        String fechaPres=txtFechaPres.getText();
        String NombrePres= txtNomPres.getText();
         Libro nuevolibro = new Libro(fechaAdq, titulo, autor, isbn, noPaginas,precio,
            leido,prestado,  fechaPres, NombrePres);
        // Escribir el libro actualizado en el archivo
        writeLibro(indice, nuevolibro);
        
        JOptionPane.showMessageDialog(this, "El libro ha sido modificado correctamente");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos en los campos correspondientes");
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error al modificar el libro");
        Logger.getLogger(ModificarGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtFechaAdqui;
    private javax.swing.JTextField txtFechaPres;
    private javax.swing.JTextField txtISDN;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextField txtLeido;
    private javax.swing.JTextField txtNoPaginas;
    private javax.swing.JTextField txtNomPres;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrestado;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
